
insert into user (id_user, nombre, email, telefono, password, avatar) values (1, 'Tamma Kyffin', 'tkyffin0@tamu.edu', '(206) 9828047', 'MuNPr9bhH4y', 'https://robohash.org/nemopariaturblanditiis.jpg?size=50x50&set=set1');
insert into user (id_user, nombre, email, telefono, password, avatar) values (2, 'Leicester Romanet', 'lromanet1@simplemachines.org', '(169) 9395611', 'oSyqMZewiwfD', 'https://robohash.org/sapienteprovidentconsectetur.jpg?size=50x50&set=set1');
insert into user (id_user, nombre, email, telefono, password, avatar) values (3, 'Chrysler Kenright', 'ckenright2@stanford.edu', '(732) 2268489', 'cWGqGIzJlRG', 'https://robohash.org/quissaepeesse.jpg?size=50x50&set=set1');
insert into user (id_user, nombre, email, telefono, password, avatar) values (4, 'Tana Scammell', 'tscammell3@epa.gov', '(332) 6774582', 'xlcq6Fi', 'https://robohash.org/repellatsitnihil.jpg?size=50x50&set=set1');
insert into user (id_user, nombre, email, telefono, password, avatar) values (5, 'Petey MacGahy', 'pmacgahy4@theatlantic.com', '(853) 9664878', 'yqwi4uAR5', 'https://robohash.org/iustolaborumdignissimos.jpg?size=50x50&set=set1');
insert into user (id_user, nombre, email, telefono, password, avatar) values (6, 'Kristyn Insley', 'kinsley5@google.nl', '(947) 1736966', 'ETkUMEHCrJ', 'https://robohash.org/eadeseruntut.jpg?size=50x50&set=set1');
insert into user (id_user, nombre, email, telefono, password, avatar) values (7, 'Luisa Giraldez', 'lgiraldez6@oaic.gov.au', '(854) 3357223', 'hcCiQB8Mme', 'https://robohash.org/cupiditatemolestiaeperspiciatis.jpg?size=50x50&set=set1');
insert into user (id_user, nombre, email, telefono, password, avatar) values (8, 'Celia Hengoed', 'chengoed7@cocolog-nifty.com', '(217) 3216539', 'sBcwHLoiL', 'https://robohash.org/assumendaaliquamveniam.jpg?size=50x50&set=set1');
insert into user (id_user, nombre, email, telefono, password, avatar) values (9, 'Barron Kubin', 'bkubin8@1688.com', '(645) 8976668', 'LqyQUZfhd', 'https://robohash.org/fugavoluptasreiciendis.jpg?size=50x50&set=set1');
insert into user (id_user, nombre, email, telefono, password, avatar) values (10, 'Latrina Chaffe', 'lchaffe9@deviantart.com', '(281) 1861787', 'BU0eyQRZnO', 'https://robohash.org/pariaturaliaspossimus.jpg?size=50x50&set=set1');
